version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--setParameter", "featureFlagSearchIndexes=true"]  # ✅ Enable Vector Search
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vector-embed:
    build: ./vector-embed
    container_name: vector-embed
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      mongodb:
        condition: service_healthy
      vector-embed:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  mongo_data:
