services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vector-embed:
    build: ./vector-embed
    container_name: vector-embed
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      mongodb:
        condition: service_healthy
      vector-embed:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      mongodb:
        condition: service_healthy
      vector-embed:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3000:3000"
    

volumes:
  mongo_data:
