version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--setParameter", "featureFlagSearchIndexes=true"]  # ✅ Enable Vector Search
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vector-embed:
    build: ./vector-embed
    container_name: vector-embed
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./vector-embed:/app  # Mount local code to sync changes in development
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: ["uvicorn", "vector-service:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Enable auto-reloading during development

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      mongodb:
        condition: service_healthy
      vector-embed:
        condition: service_healthy
    volumes:
      - ./scraper:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["watchmedo", "auto-restart", "--patterns=*.py", "--", "python", "scraper.py"]  # Watch for Python file changes and restart script

volumes:
  mongo_data:
